server.directories.data=/mnt/e/workspacce/AI/ai_kefu/.data/neo4j/data
server.directories.plugins=/mnt/e/workspacce/AI/ai_kefu/.data/neo4j/plugins
server.directories.logs=/mnt/e/workspacce/AI/ai_kefu/.data/logs/neo4j
server.directories.run=/mnt/e/workspacce/AI/ai_kefu/.data/run
server.directories.import=/mnt/e/workspacce/AI/ai_kefu/.data/neo4j/import
server.directories.lib=/mnt/e/environment/neo4j-5.26.26/usr/share/neo4j/lib
server.logs.config=/mnt/e/environment/neo4j-5.26.26/etc/neo4j/server-logs.xml
server.logs.user.config=/mnt/e/environment/neo4j-5.26.26/etc/neo4j/user-logs.xml

server.default_listen_address=127.0.0.1
server.default_advertised_address=localhost
server.bolt.enabled=true
server.bolt.listen_address=127.0.0.1:7687
server.http.enabled=true
server.http.listen_address=127.0.0.1:7474
server.https.enabled=false

initial.dbms.default_database=neo4j
dbms.security.auth_enabled=true
dbms.usage_report.enabled=false
server.memory.heap.initial_size=512m
server.memory.heap.max_size=512m
server.memory.pagecache.size=512m
