server.directories.data=E:/workspacce/AI/ai_kefu/.data/neo4j-win/data
server.directories.plugins=E:/workspacce/AI/ai_kefu/.data/neo4j-win/plugins
server.directories.logs=E:/workspacce/AI/ai_kefu/.data/logs/neo4j
server.directories.run=E:/workspacce/AI/ai_kefu/.data/run/neo4j
server.directories.import=E:/workspacce/AI/ai_kefu/.data/neo4j-win/import
server.directories.lib=E:/environment/neo4j-community-5.26.26/lib
server.logs.config=E:/environment/neo4j-community-5.26.26/conf/server-logs.xml
server.logs.user.config=E:/environment/neo4j-community-5.26.26/conf/user-logs.xml

server.default_listen_address=127.0.0.1
server.default_advertised_address=localhost
server.bolt.enabled=true
server.bolt.listen_address=127.0.0.1:7687
server.http.enabled=true
server.http.listen_address=127.0.0.1:7474
server.https.enabled=false

initial.dbms.default_database=neo4j
dbms.security.auth_enabled=true
dbms.usage_report.enabled=false
server.memory.heap.initial_size=512m
server.memory.heap.max_size=512m
server.memory.pagecache.size=512m
