bind 127.0.0.1
port 6379
daemonize yes
supervised no
pidfile /mnt/e/workspacce/AI/ai_kefu/.data/run/redis.pid
logfile /mnt/e/workspacce/AI/ai_kefu/.data/logs/redis.log
dir /mnt/e/workspacce/AI/ai_kefu/.data/redis
dbfilename dump.rdb
appendonly yes
appendfilename "appendonly.aof"
protected-mode yes
