bind 127.0.0.1
port 16380
daemonize no
supervised no
pidfile E:/workspacce/AI/ai_kefu/.data/run/redis.pid
logfile E:/workspacce/AI/ai_kefu/.data/logs/redis.log
dir E:/workspacce/AI/ai_kefu/.data/redis
dbfilename dump.rdb
appendonly yes
appendfilename "appendonly.aof"
protected-mode yes
