from __future__ import annotations

import re

from .config import SkillSystemConfig
from .frontmatter import dump_skill_frontmatter_markdown
from .schemas import SkillDraft, SkillStatus


_PHONE_RE = re.compile(r"(?<!\d)1[3-9]\d{9}(?!\d)")
_ORDER_FACT_RE = re.compile(r"(订单号|order[_ -]?id)[:：]?\s*[A-Za-z0-9-]{6,}")
_PAYMENT_FACT_RE = re.compile(r"支付状态[:：]\s*(已支付|未支付|退款中|已退款)")


def render_skill_markdown(
    draft: SkillDraft,
    *,
    config: SkillSystemConfig | None = None,
) -> str:
    if draft.frontmatter.status != SkillStatus.DRAFT:
        raise ValueError("skill draft must render with status=draft")
    if not draft.steps:
        raise ValueError("skill draft must contain at least one step")
    for step in draft.steps:
        if not step.success_criteria.strip():
            raise ValueError(f"skill step missing success criteria: {step.title}")

    body = _render_body(draft)
    if config is not None and len(body) > config.max_body_chars:
        raise ValueError("skill body exceeds max body chars")
    markdown = dump_skill_frontmatter_markdown(draft.frontmatter, body)
    _reject_realtime_facts(markdown)
    return markdown


def _render_body(draft: SkillDraft) -> str:
    lines = [
        f"# {draft.title}",
        "",
        "## Inputs",
    ]
    if draft.inputs:
        lines.extend(f"- {item}" for item in draft.inputs)
    else:
        lines.append("- 无必填参数。")

    lines.extend(["", "## Goal", "", draft.goal.strip(), "", "## Steps", ""])
    for index, step in enumerate(draft.steps, start=1):
        lines.extend(
            [
                f"### {index}. {step.title}",
                "",
                f"**Action**: {step.action.strip()}",
                "",
                f"**Success criteria**: {step.success_criteria.strip()}",
                "",
            ]
        )
        if step.artifacts:
            lines.append("**Artifacts**:")
            lines.extend(f"- {item}" for item in step.artifacts)
            lines.append("")
        if step.rules:
            lines.append("**Rules**:")
            lines.extend(f"- {item}" for item in step.rules)
            lines.append("")
        if step.human_checkpoint:
            lines.extend(
                [
                    f"**Human checkpoint**: {step.human_checkpoint.strip()}",
                    "",
                ]
            )

    lines.extend(["## Constraints", ""])
    if draft.constraints:
        lines.extend(f"- {item}" for item in draft.constraints)
    else:
        lines.append("- 不固化订单、库存、价格、物流、售后进度等实时事实；需要时必须实时查询。")

    lines.extend(["", "## Source", ""])
    if draft.source_notes:
        lines.extend(f"- {item}" for item in draft.source_notes)
    else:
        lines.append("- Generated by skillify_mvp from conversation materials.")
    lines.append("")
    return "\n".join(lines)


def _reject_realtime_facts(text: str) -> None:
    if _PHONE_RE.search(text):
        raise ValueError("skill markdown contains a concrete phone number")
    if _ORDER_FACT_RE.search(text):
        raise ValueError("skill markdown contains a concrete order identifier")
    if _PAYMENT_FACT_RE.search(text):
        raise ValueError("skill markdown contains a concrete payment status")
